echo "## 🤖 Workflow Run on $(date)" >> README.md
echo '```' >> README.md
cowsay -t tux "Hello I am a Penguin" >> README.md
echo '```' >> README.md
echo "" >> README.md
echo "Generated by GitHub Actions 🚀" >> README.md
echo "" >> README.md
git config user.name "github-actions"
git config user.email "github-actions@github.com"
git add README.md
git commit -m "Update README.md with cowsay output [skip ci]" || echo "No changes to commit"
git push

          
    