name: My first workflow

on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
        - name: Welcome message
          run : echo "my first example jobf first"
        
        - name: list files
          run : ls

        - name: cat Readme
          run : cat README.md
