name: My first workflow

on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
          - name: checkout the code
            uses: actions/checkout@v4
          
          - name: Welcome message
            run: |
              echo "my first example jobf first"
              ls -a
              cat README.md
          
          - name: Generate ASCII Artwork
            run : cowsay -f tux "Hello i am a penguin " >> penguin.txt
          
    